version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  test:  
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      - checkout
      - run: mvn clean verify
      - store_test_results:
          path: target/cucumber-reports
      - store_artifacts:
          path: target/generated-report

workflows:
  maventest: 
    jobs:
      - test
