version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  browser-tools: circleci/browser-tools@1.1.3

jobs:
  test:  
    docker:
      - image: cimg/openjdk:11.0-browsers
    steps:
      - checkout
      - run: sudo apt-get install libnss3-dev
      - restore_cache:
          key: circleci-java-selenium-{{ checksum "pom.xml" }}
      - run: mvn clean verify
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-java-selenium-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/cucumber-reports
      - store_artifacts:
          path: target/generated-report

workflows:
  maventest: 
    jobs:
      - test
